FROM grafana/grafana:13.0.2
COPY configs/grafana/datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
COPY configs/grafana/dashboards.yml /etc/grafana/provisioning/dashboards/dashboards.yml
COPY configs/grafana/overview-dashboard.json /etc/grafana/provisioning/dashboards/json/overview-dashboard.json
